name: Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: "docker-layer"
        name: "gcr.io/cloud-builders/docker"
        entrypoint: bash
        args:
          - "-c"
          - "uname -a"

      - name: Build psql image
        run: |
          docker build \
            -t psql:latest \
            -f ./.github/scripts/Dockerfile .\
          