name: Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Build psql image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./.github/scripts/Dockerfile
          push: false
          tags: psql:latest

      - name: Set db role for additional user
        run: |
          docker run \
            --entrypoint '/bin/sh' \
            psql:latest \
            -c 'chmod +x ./.github/scripts/grant-select-readonly-user.sh && ./.github/scripts/grant-select-readonly-user.sh'