name: Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build psql image
        run: |
          docker build \
            -t psql:latest \
            -f ./.github/scripts/Dockerfile .\
          

      - name: Set db role for additional user
        run: |
          docker run \
            --entrypoint '/bin/sh' \
            psql:latest \
            -c 'chmod +x /scripts/grant-select-readonly-user.sh && /scripts/grant-select-readonly-user.sh'